# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

jobs:  
- job: Build_Analyze_Test
  displayName: 'Xcode Build'
  pool:
    vmImage: 'macOS-10.14'
  variables:
    scheme: ''
    sdk: 'iphoneos13.2'
    configuration: 'Release'
  steps:
  - task: Xcode@5
    displayName: 'Xcode Clean Build'
    inputs:
      actions: 'clean build'
      sdk: '$(sdk)'
      scheme: '$(scheme)'
      configuration: '$(configuration)'
  - task: Xcode@5
    displayName: 'Xcode Analyze'
    inputs:
      actions: 'analyze'
      sdk: '$(sdk)'
      scheme: '$(scheme)'
      configuration: '$(configuration)'
  # - task: Xcode@5
  #   displayName: 
  #   inputs:
  #     actions: 'test'
  #     sdk: 'iphonesimulator'
  #     scheme: '$(scheme)'
  #     configuration: '$(configuration)'
  #     publishJUnitResults: true
- job: Package
  displayName: 'Xcode Package IPA'
  pool:
    vmImage: 'macOS-10.14'
  variables:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
  dependsOn: Build_Analyze_Test
  condition: succeeded()
  steps:
  - task: Xcode@5
    inputs:
      actions: 'build'
      sdk: '$(sdk)'
      scheme: '$(scheme)'
      configuration: '$(configuration)'
      packageApp: true