# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

jobs:  
- job: Build
  displayName: 'Xcode Build'
  pool:
    vmImage: 'macOS-10.14'
  variables:
    scheme: ''
    sdk: 'iphoneos13.2'
    configuration: 'Release'
  steps:
  - task: Xcode@5
    inputs:
      actions: 'clean build'
      sdk: '$(sdk)'
      scheme: '$(scheme)'
      configuration: '$(configuration)'
      #xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
      #exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
      #packageApp: false
- job: Analyze
  displayName: 'Xcode Analyze'
  pool:
    vmImage: 'macOS-10.14'
  variables:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
  dependsOn: Build
  condition: succeeded()
  steps:
  - task: Xcode@5
    inputs:
      actions: 'analyze'
      sdk: '$(sdk)'
      scheme: '$(scheme)'
      configuration: '$(configuration)'
      #xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
      #exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
      #packageApp: false
- job: UnitTest
  displayName: 'Xcode Test'
  pool:
    vmImage: 'macOS-10.14'
  variables:
    scheme: ''
    sdk: 'iphonesimulator'
    configuration: 'Release'
  dependsOn: Analyze
  condition: succeeded()
  steps:
  - task: Xcode@5
    inputs:
      actions: 'test'
      sdk: '$(sdk)'
      scheme: '$(scheme)'
      configuration: '$(configuration)'
      #xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
      #exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
      #packageApp: false
      publishJUnitResults: true
- job: Package
  displayName: 'Xcode Package IPA'
  pool:
    vmImage: 'macOS-10.14'
  variables:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
  dependsOn: UnitTest
  condition: succeeded()
  steps:
  - task: Xcode@5
    inputs:
      actions: 'build'
      sdk: '$(sdk)'
      scheme: '$(scheme)'
      configuration: '$(configuration)'
      #xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
      #exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
      packageApp: true